
  name: mindi
  version: '2.0.6'
  summary: A simple Video to Audio converter 
  description: 
  
  grade: devel 
  confinement: devmode 

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  apps: mindi
    get:
        command: bin/com.github.torikulhabib.mindi
